/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMockInterviewRouteImport } from './routes/_authenticated/mock-interview'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedLearnPythonRouteImport } from './routes/_authenticated/learn.python'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockInterviewRoute =
  AuthenticatedMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedLearnPythonRoute =
  AuthenticatedLearnPythonRouteImport.update({
    id: '/python',
    path: '/python',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/learn/python': typeof AuthenticatedLearnPythonRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/learn/python': typeof AuthenticatedLearnPythonRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/learn/python': typeof AuthenticatedLearnPythonRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/mock-interview'
    | '/notes'
    | '/progress'
    | '/questions'
    | '/learn/python'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mock-interview'
    | '/notes'
    | '/progress'
    | '/questions'
    | '/learn/python'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/_authenticated/mock-interview'
    | '/_authenticated/notes'
    | '/_authenticated/progress'
    | '/_authenticated/questions'
    | '/_authenticated/learn/python'
    | '/_authenticated/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-interview': {
      id: '/_authenticated/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof AuthenticatedMockInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/learn/python': {
      id: '/_authenticated/learn/python'
      path: '/python'
      fullPath: '/learn/python'
      preLoaderRoute: typeof AuthenticatedLearnPythonRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
  }
}

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnPythonRoute: typeof AuthenticatedLearnPythonRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnPythonRoute: AuthenticatedLearnPythonRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedMockInterviewRoute: typeof AuthenticatedMockInterviewRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedMockInterviewRoute: AuthenticatedMockInterviewRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
